### ISSUE TITLE
Dataset Request

### ISSUE THREAD

**Issue by ghost** [MIPT-Oulu/KneeOARSIGrading#2]
Hi Can it possible for you to share the dataset on google drive with me

**Comment by lext** [comment]
Hi,

You have to request the data from the OAI and MOST data owners.

Cheers,
-Aleksei

**Comment by ghost** [comment]
I request but it takes long time no reply from there side.

**Comment by ghost** [comment]
I have requested to access data in the Osteoarthritis Initiative but it takes 2 months from now the website is still not working
can you please share the dataset?

**Comment by Becmamba** [comment]
Hi, I want to know where to download the OARSI annotations? I can't find it.

**Comment by soupault** [comment]
The OAI data has been moved to https://nda.nih.gov/oai/ and is now easily accessible.
